var house = {
	"name":"house",
	"utilityTypes":["electricity", "heating", "water"],
	"rooms":
	[
		{
			"name":"kitchen",
			"width":"250",
			"height":"200",
			"top":"0",
			"left":"0",
			"floor":"#333333"
		},
		{
			"name":"bedroom",
			"width":"150",
			"height":"250",
			"top":"190",
			"left":"50",
			"floor":"#333333"
		},
		{
			"name":"livingroom",
			"width":"250",
			"height":"300",
			"top":"190",
			"left":"190",
			"floor":"#333333"
		},
		{
			"name":"bathroom",
			"width":"150",
			"height":"100",
			"top":"100",
			"left":"240",
			"floor":"#333333"
		}
	],
	"utilities":
	[
		{
			"type":"electricity",
			"name":"light",
			"room":"bedroom",
			"consumption":"1",
			"state":"on",
			"top":"10",
			"left":"10"
		},
		{
			"type":"electricity",
			"name":"light",
			"room":"livingroom",
			"consumption":"1",
			"state":"off",
			"top":"10",
			"left":"10"
		},
		{
			"type":"electricity",
			"name":"light",
			"room":"bathroom",
			"consumption":"1",
			"state":"off",
			"top":"10",
			"left":"10"
		},
		{
			"type":"electricity",
			"name":"light",
			"room":"kitchen",
			"consumption":"1",
			"state":"off",
			"top":"10",
			"left":"10"
		},
	],

	"furniture":[],
	"windows":[],
	"doors":[],
	"meters":
	[
		{
			"name":"electricity",
			"value":"0",
		}
	]
}